# Generated by Django 5.2.10 on 2026-02-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgricultureProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Agriculture Product',
                'verbose_name_plural': 'Agriculture Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='AutoPartsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('compatible_vehicles', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Auto Parts Product',
                'verbose_name_plural': 'Auto Parts Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('specifications', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Electronics Product',
                'verbose_name_plural': 'Electronics Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fashion Product',
                'verbose_name_plural': 'Fashion Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='FoodBeverageProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('nutritional_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Food & Beverage Product',
                'verbose_name_plural': 'Food & Beverage Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='HotelProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('check_in_policy', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hotel / Tourism Product',
                'verbose_name_plural': 'Hotel / Tourism Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('is_prescription_required', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pharmacy Product',
                'verbose_name_plural': 'Pharmacy Products',
            },
            bases=('domains.product',),
        ),
        migrations.CreateModel(
            name='RetailProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domains.product')),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Retail Product',
                'verbose_name_plural': 'Retail Products',
            },
            bases=('domains.product',),
        ),
    ]
