# Generated by Django 5.2.10 on 2026-02-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_role_can_manage_services_business_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
    ]
