# sales/views.py

from rest_framework import viewsets, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from logaccess.views import TenantScopedPermission
from logaccess.models import RoleType
from .models import Order
from .serializers import OrderSerializer, OrderCreateSerializer


class OrderViewSet(TenantScopedPermission, viewsets.ModelViewSet):
    """
    Full CRUD for orders — tenant-scoped.

    Routes (auto-generated by the router):
      GET    /api/sales/orders/       → list
      POST   /api/sales/orders/       → create
      GET    /api/sales/orders/{id}/  → retrieve
      PUT    /api/sales/orders/{id}/  → update
      PATCH  /api/sales/orders/{id}/  → partial_update
      DELETE /api/sales/orders/{id}/  → destroy
    """

    permission_classes = [IsAuthenticated]
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    # Switch to the create serializer on POST
    def get_serializer_class(self):
        if self.action == "create":
            return OrderCreateSerializer
        return OrderSerializer

    # Inject tenant + created_by — not user-supplied
    def perform_create(self, serializer):
        serializer.save(
            tenant=self.request.user.tenant,
            created_by=self.request.user,
        )

    # ── Permission gates ─────────────────────────────────────────
    def create(self, request, *args, **kwargs):
        if not request.user.has_tenant_permission(RoleType.MANAGER):
            return Response(
                {"error": "Only managers or owners can create orders."},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().create(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        if not request.user.has_tenant_permission(RoleType.MANAGER):
            return Response(
                {"error": "Only managers or owners can update orders."},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().update(request, *args, **kwargs)

    def destroy(self, request, *args, **kwargs):
        if not request.user.is_owner:
            return Response(
                {"error": "Only the owner can delete orders."},
                status=status.HTTP_403_FORBIDDEN,
            )
        return super().destroy(request, *args, **kwargs)
